In [ ]:
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np

 List VS numpy - time taken
 

In [ ]:
from time import process_time

time taken by list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0010165909999999556


In [ ]:
np_array = np.array([i for i in range(10000) ])

start_time = process_time()

np_array +=5

end_time = process_time()

print(end_time - start_time)

0.0015085610000000749


numpy array

In [ ]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating a 1d array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c  = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)

In [ ]:
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholdar in numpy *array*

In [ ]:
# create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create numpy array of one
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#creating an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# create a numpy wit random value
b = np.random.random((3,4))
print(b)

[[0.06711492 0.82860917 0.51399283 0.73640614]
 [0.77113986 0.17463    0.57253258 0.29260849]
 [0.45666668 0.21556677 0.00693111 0.98620439]]


In [ ]:
# random integer value array within a specific range
c=np.random.randint(10,100,(3,5))
print(c) 

[[60 70 75 81 43]
 [86 82 87 50 56]
 [14 11 13 48 69]]


In [ ]:
# array of evenly spaced values --> specifying the number of value required
d = np.linspace(10,30,50)
print(d)

[10.         10.40816327 10.81632653 11.2244898  11.63265306 12.04081633
 12.44897959 12.85714286 13.26530612 13.67346939 14.08163265 14.48979592
 14.89795918 15.30612245 15.71428571 16.12244898 16.53061224 16.93877551
 17.34693878 17.75510204 18.16326531 18.57142857 18.97959184 19.3877551
 19.79591837 20.20408163 20.6122449  21.02040816 21.42857143 21.83673469
 22.24489796 22.65306122 23.06122449 23.46938776 23.87755102 24.28571429
 24.69387755 25.10204082 25.51020408 25.91836735 26.32653061 26.73469388
 27.14285714 27.55102041 27.95918367 28.36734694 28.7755102  29.18367347
 29.59183673 30.        ]


In [ ]:
# array of evenly spaced value --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

analysing the numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[38 68 74 80 88]
 [72 28 54 33 49]
 [89 16 14 73 57]
 [51 89 81 31 81]
 [16 42 67 56 68]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# number of dimension 
print(c.ndim)

2


In [ ]:
# nmber of element in array
print(c.size)

25


In [ ]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operation on a np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatenate or join two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[4 1 2]
 [8 2 7]
 [7 8 5]]
[[18 15 13]
 [19 11 16]
 [17 10 10]]


In [ ]:
print(a+b)

[[22 16 15]
 [27 13 23]
 [24 18 15]]


In [ ]:
print(a-b)
print(a*b)
print(a/b)

[[-14 -14 -11]
 [-11  -9  -9]
 [-10  -2  -5]]
[[ 72  15  26]
 [152  22 112]
 [119  80  50]]
[[0.22222222 0.06666667 0.15384615]
 [0.42105263 0.18181818 0.4375    ]
 [0.41176471 0.8        0.5       ]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)
print(np.add(a,b))

[[0 6 9]
 [5 3 2]
 [7 3 8]]
[[15 11 14]
 [19 14 11]
 [19 12 17]]
[[15 17 23]
 [24 17 13]
 [26 15 25]]


In [ ]:
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[-15  -5  -5]
 [-14 -11  -9]
 [-12  -9  -9]]
[[  0  66 126]
 [ 95  42  22]
 [133  36 136]]
[[0.         0.54545455 0.64285714]
 [0.26315789 0.21428571 0.18181818]
 [0.36842105 0.25       0.47058824]]


Array manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 6 7]
 [9 2 6]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[3 9]
 [6 2]
 [7 6]]
(3, 2)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[3 9]
 [6 2]
 [7 6]]
(3, 2)


In [ ]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 0 1]
 [1 0 4]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[8 0]
 [1 1]
 [0 4]]
(3, 2)


Pandas library:
useful for data processing and analysis

panda data frame:
pandas dataframe is two-dimensional tabular data structure with labled axes(rows and columns)

In [ ]:
# import the panda library
import pandas as pd
import numpy as np

Creating pandas data frame

In [ ]:
# importing the bostan house price data
from sklearn.datasets import load_boston

In [ ]:
boston_dataset = load_boston()

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [ ]:
type(boston_dataset)

sklearn.utils.Bunch

In [ ]:
print(boston_dataset)

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]]), 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 1

In [ ]:
# pandas dataframe
boston_df = pd.DataFrame(boston_dataset.data,columns = boston_dataset.feature_names)

In [ ]:
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [ ]:
boston_df.shape

(506, 13)

In [ ]:
type(boston_df)

pandas.core.frame.DataFrame

Importing the data from csv file to a panda DataFrame


In [ ]:
# csv file to panda dataframe
diabetes_df = pd.read_csv('/content/diabetes.csv')

In [ ]:
type(diabetes_df)

pandas.core.frame.DataFrame

In [ ]:
diabetes_df.head()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
diabetes_df.shape

(768, 9)

Loading the data from a excel file to a panda Dataframe:

pd.read_excel('file path')

Exporting the Dataframe to a csv file

In [ ]:
boston_df.to_csv('boston.csv')

Exporting the panda dataframe to excel file

df.to_excel('file_name')

In [ ]:
# creating data frame with random value
random_df = pd.DataFrame(np.random.rand(20,10))

In [ ]:
random_df.head()

0         1         2         3         4         5         6  \
0  0.177305  0.684088  0.008656  0.151112  0.135370  0.409661  0.526571   
1  0.903758  0.892576  0.943090  0.156165  0.458041  0.847151  0.731339   
2  0.127710  0.358221  0.913663  0.758740  0.618931  0.493129  0.565198   
3  0.289135  0.380151  0.777898  0.057102  0.457350  0.118795  0.396023   
4  0.901444  0.838809  0.570580  0.227293  0.382736  0.993941  0.718755   

          7         8         9  
0  0.690227  0.933636  0.280445  
1  0.118217  0.368922  0.491697  
2  0.220552  0.840372  0.574711  
3  0.374800  0.597044  0.755382  
4  0.800265  0.339895  0.033732

In [ ]:
random_df.shape

(20, 10)

inspecting a dataframe

In [ ]:
# finding a number of rows and column
boston_df.shape

(506, 13)

In [ ]:
# first five row in data frame 
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [ ]:
# last 5 row of the data frame 
boston_df.tail()

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
501  0.06263  0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527  0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076  0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959  0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741  0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88

In [ ]:
# information about dataframe
boston_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
dtypes: float64(13)
memory usage: 51.5 KB


In [ ]:
# findng the number of missing value
boston_df.isnull().sum()


CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
dtype: int64

In [ ]:
# diabeties dataframe
diabetes_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
# counting the value based on the lables
diabetes_df.value_counts('Outcome')

Outcome
0    500
1    268
dtype: int64

In [ ]:
# group the values based on the scan
diabetes_df.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

Statistical measure

In [ ]:
# count or number of values 
boston_df.count()

CRIM       506
ZN         506
INDUS      506
CHAS       506
NOX        506
RM         506
AGE        506
DIS        506
RAD        506
TAX        506
PTRATIO    506
B          506
LSTAT      506
dtype: int64

In [ ]:
# mean value - column wise
boston_df.mean()

CRIM         3.613524
ZN          11.363636
INDUS       11.136779
CHAS         0.069170
NOX          0.554695
RM           6.284634
AGE         68.574901
DIS          3.795043
RAD          9.549407
TAX        408.237154
PTRATIO     18.455534
B          356.674032
LSTAT       12.653063
dtype: float64

In [ ]:
# standard deviation - column wise
boston_df.std()

CRIM         8.601545
ZN          23.322453
INDUS        6.860353
CHAS         0.253994
NOX          0.115878
RM           0.702617
AGE         28.148861
DIS          2.105710
RAD          8.707259
TAX        168.537116
PTRATIO      2.164946
B           91.294864
LSTAT        7.141062
dtype: float64

In [ ]:
# min value
boston_df.min()

CRIM         0.00632
ZN           0.00000
INDUS        0.46000
CHAS         0.00000
NOX          0.38500
RM           3.56100
AGE          2.90000
DIS          1.12960
RAD          1.00000
TAX        187.00000
PTRATIO     12.60000
B            0.32000
LSTAT        1.73000
dtype: float64

In [ ]:
# max value
boston_df.max()

CRIM        88.9762
ZN         100.0000
INDUS       27.7400
CHAS         1.0000
NOX          0.8710
RM           8.7800
AGE        100.0000
DIS         12.1265
RAD         24.0000
TAX        711.0000
PTRATIO     22.0000
B          396.9000
LSTAT       37.9700
dtype: float64

In [ ]:
# all the statical measure about the dataframe
boston_df.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

# manipulate a data frame

In [ ]:
# adding a column to a dataframe
boston_df['Price']= boston_dataset.target

In [ ]:
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  Price  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [ ]:
# removing a row
boston_df.drop(index=0,axis=0)

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
1    0.02731  0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729  0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237  0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905  0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
5    0.02985  0.0   2.18   0.0  0.458  6.430  58.7  6.0622  3.0  222.0   
..       ...  ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263  0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527  0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076  0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959  0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741  0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  Price  
1       17.8  396.90   9.14   21.6  
2       17.8  392.83   4.03   34.7  
3       18.7  394.63   2.94   33.4  
4       18.7  396.90   5.33   36.2  
5       18.7  394.12   5.21   28.7  
..       ...     ...    ...    ...  
501     21.0  391.99   9.67   22.4  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9  

[505 rows x 14 columns]

In [ ]:
# drop a column 
boston_df.drop(columns='ZN',axis=1)

CRIM  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  PTRATIO  \
0    0.00632   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0     15.3   
1    0.02731   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0     17.8   
2    0.02729   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0     17.8   
3    0.03237   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0     18.7   
4    0.06905   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0     18.7   
..       ...    ...   ...    ...    ...   ...     ...  ...    ...      ...   
501  0.06263  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0     21.0   
502  0.04527  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0     21.0   
503  0.06076  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0     21.0   
504  0.10959  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0     21.0   
505  0.04741  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0     21.0   

          B  LSTAT  Price  
0    396.90   4.98   24.0  
1    396.90   9.14   21.6  
2    392.83   4.03   34.7  
3    394.63   2.94   33.4  
4    396.90   5.33   36.2  
..      ...    ...    ...  
501  391.99   9.67   22.4  
502  396.90   9.08   20.6  
503  396.90   5.64   23.9  
504  393.45   6.48   22.0  
505  396.90   7.88   11.9  

[506 rows x 13 columns]

In [ ]:
# locating the row using the index value
boston_df.iloc[2]

CRIM         0.02729
ZN           0.00000
INDUS        7.07000
CHAS         0.00000
NOX          0.46900
RM           7.18500
AGE         61.10000
DIS          4.96710
RAD          2.00000
TAX        242.00000
PTRATIO     17.80000
B          392.83000
LSTAT        4.03000
Price       34.70000
Name: 2, dtype: float64

In [ ]:
# locating the particular column
print(boston_df.iloc[:,0])
print(boston_df.iloc[:,1])
print(boston_df.iloc[:,2])
print(boston_df.iloc[:,-1])

0      0.00632
1      0.02731
2      0.02729
3      0.03237
4      0.06905
        ...   
501    0.06263
502    0.04527
503    0.06076
504    0.10959
505    0.04741
Name: CRIM, Length: 506, dtype: float64
0      18.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
501     0.0
502     0.0
503     0.0
504     0.0
505     0.0
Name: ZN, Length: 506, dtype: float64
0       2.31
1       7.07
2       7.07
3       2.18
4       2.18
       ...  
501    11.93
502    11.93
503    11.93
504    11.93
505    11.93
Name: INDUS, Length: 506, dtype: float64
0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: Price, Length: 506, dtype: float64


## correlation 
1. positive
2. negative


In [ ]:
boston_df.corr()

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
CRIM     1.000000 -0.200469  0.406583 -0.055892  0.420972 -0.219247  0.352734   
ZN      -0.200469  1.000000 -0.533828 -0.042697 -0.516604  0.311991 -0.569537   
INDUS    0.406583 -0.533828  1.000000  0.062938  0.763651 -0.391676  0.644779   
CHAS    -0.055892 -0.042697  0.062938  1.000000  0.091203  0.091251  0.086518   
NOX      0.420972 -0.516604  0.763651  0.091203  1.000000 -0.302188  0.731470   
RM      -0.219247  0.311991 -0.391676  0.091251 -0.302188  1.000000 -0.240265   
AGE      0.352734 -0.569537  0.644779  0.086518  0.731470 -0.240265  1.000000   
DIS     -0.379670  0.664408 -0.708027 -0.099176 -0.769230  0.205246 -0.747881   
RAD      0.625505 -0.311948  0.595129 -0.007368  0.611441 -0.209847  0.456022   
TAX      0.582764 -0.314563  0.720760 -0.035587  0.668023 -0.292048  0.506456   
PTRATIO  0.289946 -0.391679  0.383248 -0.121515  0.188933 -0.355501  0.261515   
B       -0.385064  0.175520 -0.356977  0.048788 -0.380051  0.128069 -0.273534   
LSTAT    0.455621 -0.412995  0.603800 -0.053929  0.590879 -0.613808  0.602339   
Price   -0.388305  0.360445 -0.483725  0.175260 -0.427321  0.695360 -0.376955   

              DIS       RAD       TAX   PTRATIO         B     LSTAT     Price  
CRIM    -0.379670  0.625505  0.582764  0.289946 -0.385064  0.455621 -0.388305  
ZN       0.664408 -0.311948 -0.314563 -0.391679  0.175520 -0.412995  0.360445  
INDUS   -0.708027  0.595129  0.720760  0.383248 -0.356977  0.603800 -0.483725  
CHAS    -0.099176 -0.007368 -0.035587 -0.121515  0.048788 -0.053929  0.175260  
NOX     -0.769230  0.611441  0.668023  0.188933 -0.380051  0.590879 -0.427321  
RM       0.205246 -0.209847 -0.292048 -0.355501  0.128069 -0.613808  0.695360  
AGE     -0.747881  0.456022  0.506456  0.261515 -0.273534  0.602339 -0.376955  
DIS      1.000000 -0.494588 -0.534432 -0.232471  0.291512 -0.496996  0.249929  
RAD     -0.494588  1.000000  0.910228  0.464741 -0.444413  0.488676 -0.381626  
TAX     -0.534432  0.910228  1.000000  0.460853 -0.441808  0.543993 -0.468536  
PTRATIO -0.232471  0.464741  0.460853  1.000000 -0.177383  0.374044 -0.507787  
B        0.291512 -0.444413 -0.441808 -0.177383  1.000000 -0.366087  0.333461  
LSTAT   -0.496996  0.488676  0.543993  0.374044 -0.366087  1.000000 -0.737663  
Price    0.249929 -0.381626 -0.468536 -0.507787  0.333461 -0.737663  1.000000