In [1]:
import numpy as np

b = np.empty(2 , dtype = int)

In [6]:
!pip install numpy


[notice] A new release of pip available: 22.3 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [11]:
!python.exe -m pip install --upgrade pip

     ---------------------------------------- 2.1/2.1 MB 2.6 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 22.3
    Uninstalling pip-22.3:
      Successfully uninstalled pip-22.3


In [12]:
!pip install numpy

In [13]:
import numpy as np

b = np.empty(2 , dtype = int)
b

array([-1998362383,  1055193269])

In [14]:
b = np.empty([2,2] , dtype = int)

In [15]:
b

array([[ 1101751302,  -100440296],
       [ -355296188, -1625666237]])

In [16]:
b = np.empty((2,2) , dtype = int)

In [17]:
b

array([[ 1101751302,  -100440296],
       [ -355296188, -1625666237]])

In [18]:
b = np.empty([3,3])

In [19]:
b

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.11852009e-321],
       [1.37959740e-306, 2.29175545e-312, 0.00000000e+000]])

In [20]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)

In [21]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
b = np.zeros(10,dtype = int)

In [29]:
b[4] = 1

In [30]:
b

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [3]:
a = np.array([0,1,2,3])
a.shape

(4,)

In [4]:
np.random.rand()

0.4220276827335683

In [6]:
np.random.randint(10,4)

ValueError: low >= high

In [8]:
np.random.randint(10, size=(4,4))

array([[8, 4, 5, 7],
       [8, 2, 9, 3],
       [8, 8, 5, 9],
       [1, 6, 3, 5]])

In [13]:
np.random.rand(4,4)*10

array([[3.13753351, 3.82845216, 1.58088305, 9.40976289],
       [7.68338555, 5.70285287, 4.71337172, 5.02602087],
       [8.72475443, 0.48290967, 9.65050056, 4.19848885],
       [0.45406655, 7.94552112, 5.27151126, 1.2319601 ]])

In [14]:
np.arange(9,50,dtype=int)

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [15]:
np.linspace(9,49,40,dtype=int)

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 49])

In [16]:
np.eye(6,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.linspace(1,5,9)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [20]:
a = np.random.randint(1,21, size=(4,5))

In [21]:
a

array([[19,  7,  2,  1,  4],
       [ 2,  4, 17,  5, 10],
       [17, 16, 16,  5,  7],
       [18, 16,  4, 15, 13]])

In [22]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

In [23]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [24]:
a[2,0:3]

array([11, 12, 13])

In [25]:
a[1:4,3]

array([ 9, 14, 19])

In [26]:
a[2:4,0:5]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [27]:
a[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

In [28]:
a = np.array([1,2,0,0,4,0])

In [29]:
print(a[a>0])

[1 2 4]


In [30]:
ind = np.where(a>0)

In [31]:
ind

(array([0, 1, 4], dtype=int64),)

In [34]:
a = np.arange(1,20,2)

In [35]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [36]:
print(np.where(a%3==0))

(array([1, 4, 7], dtype=int64),)


In [39]:
a = np.arange(1,11)

In [40]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
a[a%2!=0]=-1

In [43]:
a


array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [51]:
a = np.random.randint(1,10, size =(1,10))

In [52]:
a


array([[9, 7, 8, 6, 9, 2, 2, 7, 7, 6]])

In [53]:
a = np.array([11,2,13,4,15,6,27,8,19])

In [54]:
a

array([11,  2, 13,  4, 15,  6, 27,  8, 19])

In [55]:
b = a.argmax()

In [56]:
b

6

In [57]:
a[b]=0

In [58]:
a

array([11,  2, 13,  4, 15,  6,  0,  8, 19])

In [59]:
a = np.arange(1,11)

In [60]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
print(a[(a<4) | (a>8)])

[ 1  2  3  9 10]


In [63]:
a = np.random.randint(15,20, size =(1,20))

In [64]:
a

array([[15, 19, 18, 16, 17, 17, 19, 18, 17, 16, 15, 18, 15, 15, 16, 16,
        18, 16, 17, 18]])

In [65]:
b = np.random.randint(150,160, size =(1,20))

In [66]:
b


array([[156, 152, 156, 156, 158, 153, 150, 154, 154, 155, 150, 153, 156,
        151, 157, 157, 155, 153, 153, 154]])

In [67]:
ind = np.where(b>155)

In [68]:
age = a[ind]

In [69]:
print(age)
print(b[ind])

[15 18 16 17 15 16 16]
[156 156 156 158 156 157 157]


In [2]:
a = np.random.randint(1,30,(5,6))

In [3]:
a

array([[10,  3,  6, 10, 23, 21],
       [26, 17, 17,  4, 15,  2],
       [ 6, 16,  7,  8, 15, 13],
       [28, 26, 19,  2, 27, 28],
       [ 1, 23, 27,  8, 25, 10]])

In [4]:
bool_arr = a>20
bool_arr

array([[False, False, False, False,  True,  True],
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True,  True, False, False,  True,  True],
       [False,  True,  True, False,  True, False]])

In [5]:
ans = a[bool_arr]
print(ans)

[23 21 26 28 26 27 28 23 27 25]


In [6]:
b = a
print(a)

[[10  3  6 10 23 21]
 [26 17 17  4 15  2]
 [ 6 16  7  8 15 13]
 [28 26 19  2 27 28]
 [ 1 23 27  8 25 10]]


In [7]:
b[bool_arr]=100
print(b)

[[ 10   3   6  10 100 100]
 [100  17  17   4  15   2]
 [  6  16   7   8  15  13]
 [100 100  19   2 100 100]
 [  1 100 100   8 100  10]]


In [8]:
a = np.random.randint(1,10,(2,2))

In [9]:
a

array([[1, 6],
       [6, 8]])

In [10]:
print(b)

[[ 10   3   6  10 100 100]
 [100  17  17   4  15   2]
 [  6  16   7   8  15  13]
 [100 100  19   2 100 100]
 [  1 100 100   8 100  10]]


In [16]:
bool_arr = b[:,4]==100
print(bool_arr)

[ True False False  True  True]


In [17]:
 b[bool_arr, 4]=99

In [18]:
print(b)

[[ 10   3   6  10  99 100]
 [100  17  17   4  15   2]
 [  6  16   7   8  15  13]
 [100 100  19   2  99 100]
 [  1 100 100   8  99  10]]


In [28]:
arr = np.array([[21,20,19,18,17],[16,15,14,13,12],[11,10,9,8,7],[6,5,4,3,2]])

In [29]:
print(arr)

[[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]


In [30]:
ans = arr[arr[:,0].argsort()]

In [31]:
ans

array([[ 6,  5,  4,  3,  2],
       [11, 10,  9,  8,  7],
       [16, 15, 14, 13, 12],
       [21, 20, 19, 18, 17]])

In [32]:
brr = arr[:,arr[0,:].argsort()]

In [33]:
brr

array([[17, 18, 19, 20, 21],
       [12, 13, 14, 15, 16],
       [ 7,  8,  9, 10, 11],
       [ 2,  3,  4,  5,  6]])

In [34]:
g = np.random.randint(1,5,(2,5))

In [35]:
g

array([[3, 4, 1, 1, 4],
       [2, 2, 4, 3, 4]])

In [36]:
np.resize(g,(1,3))

array([[3, 4, 1]])

In [44]:
import csv

file_obj = open('D:\programming language\Data science and Machine learning\code\year2017.csv')
data = csv.DictReader(file_obj,skipinitialspace = True)


killed = []
wounded = []
country = []
for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    wounded.append(row['Wounded'])   
    
np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_country = np.array(country)

np_killed[np_killed == '']='0.0'
np_wounded[np_wounded=='']='0.0'

np_killed = np.array(np_killed,dtype = float)
np_wounded = np.array(np_wounded,dtype = float)

killed_wounded = np_killed + np_wounded
killed_wounded

booarr = np_country == 'India'

ans = killed_wounded[booarr]
print(np.sum(ans))
print(np.sum(killed_wounded))


1167.0
51372.0
